apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowledge-tree.fullname" . }}-config
  labels:
    {{- include "knowledge-tree.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.configYaml | toYaml | nindent 4 }}
