apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowledge-tree.fullname" . }}-hatchet
  labels:
    {{- include "knowledge-tree.componentLabels" (dict "root" . "component" "hatchet") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
      protocol: TCP
    - port: 7070
      targetPort: 7070
      name: grpc
      protocol: TCP
  selector:
    {{- include "knowledge-tree.componentSelectorLabels" (dict "root" . "component" "hatchet") | nindent 4 }}
