"""initial schema

Revision ID: 3256dd2096fd
Revises:
Create Date: 2026-02-13 17:41:02.880503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import UserDefinedType


class Vector(UserDefinedType):  # type: ignore[type-arg]
    """Minimal Vector type for migration compatibility (pgvector removed)."""
    def __init__(self, dim: int) -> None:
        self.dim = dim
    def get_col_spec(self) -> str:
        return f"vector({self.dim})"
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3256dd2096fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('known_biases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fact_type', sa.String(length=50), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept', sa.String(length=500), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('attractor', sa.String(length=500), nullable=True),
    sa.Column('filter_id', sa.String(length=100), nullable=True),
    sa.Column('max_content_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('stale_after', sa.Integer(), nullable=False),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_concept'), 'nodes', ['concept'], unique=False)
    op.create_table('provider_fetches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('fetch_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_origins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_sources_content_hash'), 'raw_sources', ['content_hash'], unique=True)
    op.create_table('convergence_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('convergence_score', sa.Float(), nullable=False),
    sa.Column('converged_claims', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('recommended_content', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_table('dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggested_concepts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('model_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_by_query', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by_query'], ['query_origins.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', 'relationship_type', name='uq_edge_source_target_type')
    )
    op.create_table('fact_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('raw_source_id', sa.UUID(), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('attribution', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_source_id'], ['raw_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_facts',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'fact_id'),
    sa.UniqueConstraint('node_id', 'fact_id', name='uq_node_fact')
    )
    op.create_table('node_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divergent_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('model_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('divergence_type', sa.String(length=100), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['convergence_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('divergent_claims')
    op.drop_table('node_versions')
    op.drop_table('node_facts')
    op.drop_table('fact_sources')
    op.drop_table('edges')
    op.drop_table('dimensions')
    op.drop_table('convergence_reports')
    op.drop_index(op.f('ix_raw_sources_content_hash'), table_name='raw_sources')
    op.drop_table('raw_sources')
    op.drop_table('query_origins')
    op.drop_table('provider_fetches')
    op.drop_index(op.f('ix_nodes_concept'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_table('facts')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
