"""initial_schema

Revision ID: 489643109ccd
Revises:
Create Date: 2026-04-15 18:23:00.275348

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import kt_db.encrypted_type

# revision identifiers, used by Alembic.
revision: str = "489643109ccd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required extensions for trigram/FTS indexes used by the graph-db.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("known_biases", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("model_id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("mode", sa.String(length=20), server_default="research", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "database_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("config_key", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_key"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "facts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("fact_type", sa.String(length=50), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "graph_groups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=100), nullable=True),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_llm_usage_conversation_id", "llm_usage", ["conversation_id"], unique=False)
    op.create_index("ix_llm_usage_created_at", "llm_usage", ["created_at"], unique=False)
    op.create_index("ix_llm_usage_message_id", "llm_usage", ["message_id"], unique=False)
    op.create_index("ix_llm_usage_model_id", "llm_usage", ["model_id"], unique=False)
    op.create_index("ix_llm_usage_task_type", "llm_usage", ["task_type"], unique=False)
    op.create_table(
        "oauth_clients",
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("client_secret", kt_db.encrypted_type.EncryptedString(), nullable=True),
        sa.Column("client_id_issued_at", sa.Integer(), nullable=True),
        sa.Column("client_secret_expires_at", sa.Integer(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("client_id"),
    )
    op.create_table(
        "provider_fetches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("fetch_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "query_origins",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "raw_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("uri", sa.String(length=2000), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_full_text", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("provider_id", sa.String(length=100), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fact_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("prohibited_chunk_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_super_source", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("fetch_attempted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("fetch_error", sa.String(length=1000), nullable=True),
        sa.Column("access_groups", postgresql.ARRAY(sa.String(length=500)), nullable=True),
        sa.Column("canonical_url", sa.String(length=2000), nullable=True),
        sa.Column("doi", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_raw_sources_canonical_url"), "raw_sources", ["canonical_url"], unique=False)
    op.create_index(op.f("ix_raw_sources_content_hash"), "raw_sources", ["content_hash"], unique=False)
    op.create_index(op.f("ix_raw_sources_doi"), "raw_sources", ["doi"], unique=False)
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "user",
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("encrypted_openrouter_key", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("graph_slugs", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("nav_budget", sa.Integer(), nullable=True),
        sa.Column("explore_budget", sa.Integer(), nullable=True),
        sa.Column("nav_used", sa.Integer(), nullable=True),
        sa.Column("explore_used", sa.Integer(), nullable=True),
        sa.Column("visited_nodes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_nodes", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_edges", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("subgraph", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("workflow_run_id", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fact_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.Column("raw_source_id", sa.UUID(), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("author_person", sa.String(length=500), nullable=True),
        sa.Column("author_org", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["raw_source_id"], ["raw_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fact_id", "raw_source_id", name="uq_fact_source"),
    )
    op.create_table(
        "graph_group_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["graph_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_graph_group_member"),
    )
    op.create_index(op.f("ix_graph_group_members_group_id"), "graph_group_members", ["group_id"], unique=False)
    op.create_index(op.f("ix_graph_group_members_user_id"), "graph_group_members", ["user_id"], unique=False)
    op.create_table(
        "graphs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("contribute_to_public", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("use_public_cache", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("graph_type", sa.String(length=20), server_default="v1", nullable=False),
        sa.Column("byok_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("storage_mode", sa.String(length=20), server_default="schema", nullable=False),
        sa.Column("schema_name", sa.String(length=100), nullable=False),
        sa.Column("database_connection_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="provisioning", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["database_connection_id"], ["database_connections.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graphs_slug"), "graphs", ["slug"], unique=True)
    op.create_table(
        "ingest_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("original_name", sa.String(length=500), nullable=False),
        sa.Column("stored_path", sa.String(length=1000), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("raw_source_id", sa.UUID(), nullable=True),
        sa.Column("section_count", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["raw_source_id"], ["raw_sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(), nullable=True),
        sa.Column("redeemed_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["redeemed_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invites_code"), "invites", ["code"], unique=True)
    op.create_index(op.f("ix_invites_email"), "invites", ["email"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("concept", sa.String(length=500), nullable=False),
        sa.Column("attractor", sa.String(length=500), nullable=True),
        sa.Column("filter_id", sa.String(length=100), nullable=True),
        sa.Column("max_content_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("node_type", sa.String(length=20), server_default="concept", nullable=False),
        sa.Column("entity_subtype", sa.String(length=20), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("source_concept_id", sa.UUID(), nullable=True),
        sa.Column("stale_after", sa.Integer(), nullable=False),
        sa.Column("update_count", sa.Integer(), nullable=False),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("definition_source", sa.String(length=100), nullable=True),
        sa.Column("definition_generated_at", sa.DateTime(), nullable=True),
        sa.Column("enrichment_status", sa.String(length=20), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("visibility", sa.String(length=20), server_default="public", nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=True),
        sa.Column("fact_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("edge_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("child_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("dimension_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("convergence_score", sa.Float(), server_default="0.0", nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_id"], ["nodes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_concept_id"], ["nodes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodes_concept"), "nodes", ["concept"], unique=False)
    op.create_index(op.f("ix_nodes_entity_subtype"), "nodes", ["entity_subtype"], unique=False)
    op.create_index(op.f("ix_nodes_node_type"), "nodes", ["node_type"], unique=False)
    op.create_table(
        "oauth_access_tokens",
        sa.Column("token", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.client_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "oauth_account",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("oauth_name", sa.String(length=100), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(length=1024), nullable=True),
        sa.Column("account_id", sa.String(length=320), nullable=False),
        sa.Column("account_email", sa.String(length=320), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_account_account_id"), "oauth_account", ["account_id"], unique=False)
    op.create_index(op.f("ix_oauth_account_oauth_name"), "oauth_account", ["oauth_name"], unique=False)
    op.create_table(
        "oauth_authorization_codes",
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("redirect_uri_provided_explicitly", sa.Boolean(), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("code_challenge", sa.String(length=200), nullable=False),
        sa.Column("resource", sa.String(length=500), nullable=True),
        sa.Column("state", sa.String(length=200), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("csrf_token", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.client_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "oauth_refresh_tokens",
        sa.Column("token", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("access_token", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.client_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_table(
        "page_fetch_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("raw_source_id", sa.UUID(), nullable=True),
        sa.Column("fact_count", sa.Integer(), nullable=False),
        sa.Column("skip_reason", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["raw_source_id"], ["raw_sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_fetch_log_url"), "page_fetch_log", ["url"], unique=True)
    op.create_table(
        "prohibited_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_source_id", sa.UUID(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("fallback_model_id", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["raw_source_id"], ["raw_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "waitlist_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["reviewed_by"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_waitlist_entries_email"), "waitlist_entries", ["email"], unique=False)
    op.create_table(
        "convergence_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("convergence_score", sa.Float(), nullable=False),
        sa.Column("converged_claims", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("recommended_content", sa.Text(), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id"),
    )
    op.create_table(
        "dimensions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("suggested_concepts", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("model_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("batch_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fact_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_definitive", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_node_id", sa.UUID(), nullable=False),
        sa.Column("target_node_id", sa.UUID(), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("created_by_query", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("weight_source", sa.String(length=20), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_query"],
            ["query_origins.id"],
        ),
        sa.ForeignKeyConstraint(["source_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_node_id", "target_node_id", "relationship_type", name="uq_edge_source_target_type"),
    )
    op.create_table(
        "graph_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["graph_id"], ["graphs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("graph_id", "user_id", name="uq_graph_member"),
    )
    op.create_index(op.f("ix_graph_members_graph_id"), "graph_members", ["graph_id"], unique=False)
    op.create_index(op.f("ix_graph_members_user_id"), "graph_members", ["user_id"], unique=False)
    op.create_table(
        "node_counters",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("access_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("update_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("seed_fact_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_table(
        "node_fact_rejections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.Column("rejected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id", "fact_id", name="uq_node_fact_rejection"),
    )
    op.create_index("ix_node_fact_rejections_node_id", "node_fact_rejections", ["node_id"], unique=False)
    op.create_table(
        "node_facts",
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("stance", sa.String(length=20), nullable=True),
        sa.Column("linked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("node_id", "fact_id"),
        sa.UniqueConstraint("node_id", "fact_id", name="uq_node_fact"),
    )
    op.create_table(
        "node_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_node_count", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "research_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("workflow_run_id", sa.String(length=255), nullable=True),
        sa.Column("summary_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("nodes_created", sa.Integer(), nullable=False),
        sa.Column("edges_created", sa.Integer(), nullable=False),
        sa.Column("waves_completed", sa.Integer(), nullable=False),
        sa.Column("explore_budget", sa.Integer(), nullable=True),
        sa.Column("explore_used", sa.Integer(), nullable=False),
        sa.Column("nav_budget", sa.Integer(), nullable=True),
        sa.Column("nav_used", sa.Integer(), nullable=False),
        sa.Column("scope_summaries", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("total_prompt_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_completion_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_cost_usd", sa.Float(), server_default="0.0", nullable=False),
        sa.Column("usage_by_task", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("super_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("report_type", sa.String(length=30), server_default="research", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["conversation_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    op.create_index(op.f("ix_research_reports_conversation_id"), "research_reports", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_research_reports_workflow_run_id"), "research_reports", ["workflow_run_id"], unique=False)
    op.create_table(
        "dimension_facts",
        sa.Column("dimension_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.Column("linked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["dimension_id"], ["dimensions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("dimension_id", "fact_id"),
        sa.UniqueConstraint("dimension_id", "fact_id", name="uq_dimension_fact"),
    )
    op.create_table(
        "divergent_claims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("model_positions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("divergence_type", sa.String(length=100), nullable=True),
        sa.Column("analysis", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["convergence_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edge_facts",
        sa.Column("edge_id", sa.UUID(), nullable=False),
        sa.Column("fact_id", sa.UUID(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("linked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["edge_id"], ["edges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("edge_id", "fact_id"),
        sa.UniqueConstraint("edge_id", "fact_id", name="uq_edge_fact"),
    )
    op.create_table(
        "llm_usage_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("research_report_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.String(length=200), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["research_report_id"], ["research_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_usage_records_research_report_id"), "llm_usage_records", ["research_report_id"], unique=False
    )
    # ### end Alembic commands ###

    # Trigram indexes — cannot be autogenerated, require pg_trgm extension.
    op.execute("CREATE INDEX ix_facts_content_trgm ON public.facts USING gin (content public.gin_trgm_ops)")
    op.execute(
        "CREATE INDEX ix_fact_sources_author_org_trgm ON public.fact_sources "
        "USING gin (author_org public.gin_trgm_ops) WHERE (author_org IS NOT NULL)"
    )
    op.execute("CREATE INDEX ix_raw_sources_uri_trgm ON public.raw_sources USING gin (uri public.gin_trgm_ops)")

    # Partial / expression indexes autogenerate cannot emit.
    op.execute("CREATE INDEX ix_nodes_parent_id ON public.nodes USING btree (parent_id) WHERE (parent_id IS NOT NULL)")
    op.execute(
        "CREATE INDEX ix_nodes_composite ON public.nodes "
        "USING btree (node_type) WHERE "
        "((node_type)::text = ANY "
        "((ARRAY['synthesis'::character varying, 'perspective'::character varying])::text[]))"
    )
    op.execute(
        "CREATE INDEX ix_nodes_synth_visibility ON public.nodes "
        "USING btree (node_type, visibility, created_at DESC) WHERE "
        "((node_type)::text = ANY "
        "((ARRAY['synthesis'::character varying, 'supersynthesis'::character varying])::text[]))"
    )

    # Foreign-key lookup indexes not declared on the ORM columns.
    for idx_sql in (
        "CREATE INDEX ix_api_tokens_user_id ON public.api_tokens (user_id)",
        "CREATE INDEX ix_conversation_messages_conversation_id ON public.conversation_messages (conversation_id)",
        "CREATE INDEX ix_dimension_facts_fact_id ON public.dimension_facts (fact_id)",
        "CREATE INDEX ix_dimensions_node_id ON public.dimensions (node_id)",
        "CREATE INDEX ix_edge_facts_fact_id ON public.edge_facts (fact_id)",
        "CREATE INDEX ix_edges_source_node_id ON public.edges (source_node_id)",
        "CREATE INDEX ix_edges_target_node_id ON public.edges (target_node_id)",
        "CREATE INDEX ix_fact_sources_fact_id ON public.fact_sources (fact_id)",
        "CREATE INDEX ix_fact_sources_raw_source_id ON public.fact_sources (raw_source_id)",
        "CREATE INDEX ix_ingest_sources_conversation_id ON public.ingest_sources (conversation_id)",
        "CREATE INDEX ix_node_fact_rejections_fact_id ON public.node_fact_rejections (fact_id)",
        "CREATE INDEX ix_node_facts_fact_id ON public.node_facts (fact_id)",
        "CREATE INDEX ix_node_versions_node_id ON public.node_versions (node_id)",
        "CREATE INDEX ix_oauth_account_oauth_name_account_id ON public.oauth_account (oauth_name, account_id)",
        "CREATE INDEX ix_oauth_refresh_tokens_access_token ON public.oauth_refresh_tokens (access_token)",
        "CREATE INDEX ix_prohibited_chunks_raw_source_id ON public.prohibited_chunks (raw_source_id)",
    ):
        op.execute(idx_sql)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_usage_records_research_report_id"), table_name="llm_usage_records")
    op.drop_table("llm_usage_records")
    op.drop_table("edge_facts")
    op.drop_table("divergent_claims")
    op.drop_table("dimension_facts")
    op.drop_index(op.f("ix_research_reports_workflow_run_id"), table_name="research_reports")
    op.drop_index(op.f("ix_research_reports_conversation_id"), table_name="research_reports")
    op.drop_table("research_reports")
    op.drop_table("node_versions")
    op.drop_table("node_facts")
    op.drop_index("ix_node_fact_rejections_node_id", table_name="node_fact_rejections")
    op.drop_table("node_fact_rejections")
    op.drop_table("node_counters")
    op.drop_index(op.f("ix_graph_members_user_id"), table_name="graph_members")
    op.drop_index(op.f("ix_graph_members_graph_id"), table_name="graph_members")
    op.drop_table("graph_members")
    op.drop_table("edges")
    op.drop_table("dimensions")
    op.drop_table("convergence_reports")
    op.drop_index(op.f("ix_waitlist_entries_email"), table_name="waitlist_entries")
    op.drop_table("waitlist_entries")
    op.drop_table("prohibited_chunks")
    op.drop_index(op.f("ix_page_fetch_log_url"), table_name="page_fetch_log")
    op.drop_table("page_fetch_log")
    op.drop_table("oauth_refresh_tokens")
    op.drop_table("oauth_authorization_codes")
    op.drop_index(op.f("ix_oauth_account_oauth_name"), table_name="oauth_account")
    op.drop_index(op.f("ix_oauth_account_account_id"), table_name="oauth_account")
    op.drop_table("oauth_account")
    op.drop_table("oauth_access_tokens")
    op.drop_index(op.f("ix_nodes_node_type"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_entity_subtype"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_concept"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_invites_email"), table_name="invites")
    op.drop_index(op.f("ix_invites_code"), table_name="invites")
    op.drop_table("invites")
    op.drop_table("ingest_sources")
    op.drop_index(op.f("ix_graphs_slug"), table_name="graphs")
    op.drop_table("graphs")
    op.drop_index(op.f("ix_graph_group_members_user_id"), table_name="graph_group_members")
    op.drop_index(op.f("ix_graph_group_members_group_id"), table_name="graph_group_members")
    op.drop_table("graph_group_members")
    op.drop_table("fact_sources")
    op.drop_table("conversation_messages")
    op.drop_table("api_tokens")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("system_settings")
    op.drop_index(op.f("ix_raw_sources_doi"), table_name="raw_sources")
    op.drop_index(op.f("ix_raw_sources_content_hash"), table_name="raw_sources")
    op.drop_index(op.f("ix_raw_sources_canonical_url"), table_name="raw_sources")
    op.drop_table("raw_sources")
    op.drop_table("query_origins")
    op.drop_table("provider_fetches")
    op.drop_table("oauth_clients")
    op.drop_index("ix_llm_usage_task_type", table_name="llm_usage")
    op.drop_index("ix_llm_usage_model_id", table_name="llm_usage")
    op.drop_index("ix_llm_usage_message_id", table_name="llm_usage")
    op.drop_index("ix_llm_usage_created_at", table_name="llm_usage")
    op.drop_index("ix_llm_usage_conversation_id", table_name="llm_usage")
    op.drop_table("llm_usage")
    op.drop_table("graph_groups")
    op.drop_table("facts")
    op.drop_table("database_connections")
    op.drop_table("conversations")
    op.drop_table("ai_models")
    # ### end Alembic commands ###
