"""initial_schema

Revision ID: 5f38f1bac3ef
Revises: 
Create Date: 2026-04-15 18:24:00.021132

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f38f1bac3ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required extensions for trigram / phonetic matching used by the write-db.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS fuzzystrmatch")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_key', sa.String(length=1200), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('graph_slug', sa.String(length=100), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_failures_next_retry_at', 'sync_failures', ['next_retry_at'], unique=False)
    op.create_index('ix_sync_failures_status', 'sync_failures', ['status'], unique=False)
    op.create_table('sync_watermarks',
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('graph_slug', sa.String(length=100), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'graph_slug')
    )
    op.create_table('write_convergence_reports',
    sa.Column('node_key', sa.String(length=500), nullable=False),
    sa.Column('convergence_score', sa.Float(), nullable=False),
    sa.Column('converged_claims', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('recommended_content', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('node_key')
    )
    op.create_index('ix_write_convergence_updated_at', 'write_convergence_reports', ['updated_at'], unique=False)
    op.create_table('write_dimensions',
    sa.Column('key', sa.String(length=800), nullable=False),
    sa.Column('node_key', sa.String(length=500), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggested_concepts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('batch_index', sa.Integer(), nullable=False),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('is_definitive', sa.Boolean(), nullable=False),
    sa.Column('fact_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_write_dimensions_node_key', 'write_dimensions', ['node_key'], unique=False)
    op.create_index('ix_write_dimensions_updated_at', 'write_dimensions', ['updated_at'], unique=False)
    op.create_table('write_divergent_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(length=500), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('model_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('divergence_type', sa.String(length=100), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_divergent_claims_node_key', 'write_divergent_claims', ['node_key'], unique=False)
    op.create_index('ix_write_divergent_claims_updated_at', 'write_divergent_claims', ['updated_at'], unique=False)
    op.create_table('write_edge_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seed_key_a', sa.String(length=500), nullable=False),
    sa.Column('seed_key_b', sa.String(length=500), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discovery_strategy', sa.String(length=50), nullable=True),
    sa.Column('evaluation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key_a', 'seed_key_b', 'fact_id', name='uq_wec_pair_fact')
    )
    op.create_index('ix_wec_seed_a_status', 'write_edge_candidates', ['seed_key_a', 'status'], unique=False)
    op.create_index('ix_wec_seed_b_status', 'write_edge_candidates', ['seed_key_b', 'status'], unique=False)
    op.create_table('write_edges',
    sa.Column('key', sa.String(length=1200), nullable=False),
    sa.Column('source_node_key', sa.String(length=500), nullable=False),
    sa.Column('target_node_key', sa.String(length=500), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('weight_source', sa.String(length=20), nullable=True),
    sa.Column('fact_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_write_edges_source_key', 'write_edges', ['source_node_key'], unique=False)
    op.create_index('ix_write_edges_target_key', 'write_edges', ['target_node_key'], unique=False)
    op.create_index('ix_write_edges_updated_at', 'write_edges', ['updated_at'], unique=False)
    op.create_table('write_fact_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('raw_source_uri', sa.String(length=2000), nullable=False),
    sa.Column('raw_source_title', sa.String(length=1000), nullable=True),
    sa.Column('raw_source_content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_source_provider_id', sa.String(length=100), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('author_person', sa.String(length=500), nullable=True),
    sa.Column('author_org', sa.String(length=500), nullable=True),
    sa.Column('access_groups', postgresql.ARRAY(sa.String(length=500)), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_fact_sources_fact_id', 'write_fact_sources', ['fact_id'], unique=False)
    op.create_index('ix_write_fact_sources_updated_at', 'write_fact_sources', ['updated_at'], unique=False)
    op.create_table('write_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fact_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedup_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_facts_dedup_pending', 'write_facts', ['created_at'], unique=False, postgresql_where=sa.text("dedup_status IN ('pending', 'in_progress')"))
    op.create_index('ix_write_facts_fact_type', 'write_facts', ['fact_type'], unique=False)
    op.create_index('ix_write_facts_updated_at', 'write_facts', ['updated_at'], unique=False)
    op.create_table('write_llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_llm_usage_conversation_id', 'write_llm_usage', ['conversation_id'], unique=False)
    op.create_index('ix_write_llm_usage_message_id', 'write_llm_usage', ['message_id'], unique=False)
    op.create_index('ix_write_llm_usage_task_type', 'write_llm_usage', ['task_type'], unique=False)
    op.create_index('ix_write_llm_usage_updated_at', 'write_llm_usage', ['updated_at'], unique=False)
    op.create_table('write_node_counters',
    sa.Column('node_key', sa.String(length=500), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('seed_fact_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('node_key')
    )
    op.create_index('ix_write_node_counters_updated_at', 'write_node_counters', ['updated_at'], unique=False)
    op.create_table('write_node_fact_rejections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_nfr_node_id', 'write_node_fact_rejections', ['node_id'], unique=False)
    op.create_index('ix_write_nfr_updated_at', 'write_node_fact_rejections', ['updated_at'], unique=False)
    op.create_index('uq_write_nfr_node_fact', 'write_node_fact_rejections', ['node_id', 'fact_id'], unique=True)
    op.create_table('write_node_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(length=500), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_node_count', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_node_versions_node_key', 'write_node_versions', ['node_key'], unique=False)
    op.create_index('ix_write_node_versions_updated_at', 'write_node_versions', ['updated_at'], unique=False)
    op.create_table('write_nodes',
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('node_uuid', sa.UUID(), nullable=False),
    sa.Column('concept', sa.String(length=500), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('entity_subtype', sa.String(length=20), nullable=True),
    sa.Column('parent_key', sa.String(length=500), nullable=True),
    sa.Column('source_concept_key', sa.String(length=500), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('definition_source', sa.String(length=100), nullable=True),
    sa.Column('attractor', sa.String(length=500), nullable=True),
    sa.Column('filter_id', sa.String(length=100), nullable=True),
    sa.Column('max_content_tokens', sa.Integer(), nullable=False),
    sa.Column('stale_after', sa.Integer(), nullable=False),
    sa.Column('fact_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('enrichment_status', sa.String(length=20), nullable=True),
    sa.Column('facts_at_last_build', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_write_nodes_node_type', 'write_nodes', ['node_type'], unique=False)
    op.create_index('ix_write_nodes_node_uuid', 'write_nodes', ['node_uuid'], unique=True)
    op.create_index('ix_write_nodes_updated_at', 'write_nodes', ['updated_at'], unique=False)
    op.create_table('write_page_fetch_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('raw_source_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fact_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skip_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_page_fetch_log_updated_at', 'write_page_fetch_log', ['updated_at'], unique=False)
    op.create_index('ix_write_page_fetch_log_url', 'write_page_fetch_log', ['url'], unique=True)
    op.create_table('write_prohibited_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('fallback_model_id', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('fallback_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_prohibited_chunks_content_hash', 'write_prohibited_chunks', ['source_content_hash'], unique=False)
    op.create_index('ix_write_prohibited_chunks_updated_at', 'write_prohibited_chunks', ['updated_at'], unique=False)
    op.create_table('write_raw_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uri', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_full_text', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('prohibited_chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_super_source', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fetch_attempted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fetch_error', sa.String(length=1000), nullable=True),
    sa.Column('canonical_url', sa.String(length=2000), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('contributed_to_public_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_raw_sources_canonical_url', 'write_raw_sources', ['canonical_url'], unique=False)
    op.create_index('ix_write_raw_sources_content_hash', 'write_raw_sources', ['content_hash'], unique=True)
    op.create_index('ix_write_raw_sources_doi', 'write_raw_sources', ['doi'], unique=False)
    op.create_index('ix_write_raw_sources_updated_at', 'write_raw_sources', ['updated_at'], unique=False)
    op.create_index('ix_write_raw_sources_uri', 'write_raw_sources', ['uri'], unique=False)
    op.create_table('write_seed_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seed_key', sa.String(length=500), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_context', sa.Text(), nullable=True),
    sa.Column('extraction_role', sa.String(length=30), server_default='mentioned', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_seed_facts_seed_key', 'write_seed_facts', ['seed_key'], unique=False)
    op.create_index('ix_write_seed_facts_updated_at', 'write_seed_facts', ['updated_at'], unique=False)
    op.create_index('uq_wsf_seed_fact', 'write_seed_facts', ['seed_key', 'fact_id'], unique=True)
    op.create_table('write_seed_merges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('source_seed_key', sa.String(length=500), nullable=False),
    sa.Column('target_seed_key', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('fact_ids_moved', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_write_seed_merges_updated_at', 'write_seed_merges', ['updated_at'], unique=False)
    op.create_table('write_seed_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_seed_key', sa.String(length=500), nullable=False),
    sa.Column('child_seed_key', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('ambiguity_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_seed_key', 'child_seed_key', name='uq_wsr_parent_child')
    )
    op.create_index('ix_wsr_child_seed_key', 'write_seed_routes', ['child_seed_key'], unique=False)
    op.create_index('ix_wsr_parent_seed_key', 'write_seed_routes', ['parent_seed_key'], unique=False)
    op.create_table('write_seeds',
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('seed_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('entity_subtype', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('merged_into_key', sa.String(length=500), nullable=True),
    sa.Column('promoted_node_key', sa.String(length=500), nullable=True),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('phonetic_code', sa.String(length=50), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=500)), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_write_seeds_phonetic_code', 'write_seeds', ['phonetic_code'], unique=False)
    op.create_index('ix_write_seeds_seed_uuid', 'write_seeds', ['seed_uuid'], unique=True)
    op.create_index('ix_write_seeds_status', 'write_seeds', ['status'], unique=False)
    op.create_index('ix_write_seeds_updated_at', 'write_seeds', ['updated_at'], unique=False)
    # ### end Alembic commands ###

    # Trigram indexes — require pg_trgm extension, cannot be autogenerated.
    op.execute(
        "CREATE INDEX ix_write_nodes_concept_trgm ON public.write_nodes "
        "USING gin (concept public.gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_write_seeds_name_trgm ON public.write_seeds "
        "USING gin (name public.gin_trgm_ops)"
    )

    # Additional indexes autogenerate does not derive (GIN on arrays,
    # partial predicates, composite FK + status lookups).
    for idx_sql in (
        "CREATE INDEX ix_write_nodes_entity_subtype ON public.write_nodes (entity_subtype)",
        "CREATE INDEX ix_write_nodes_fact_ids_gin ON public.write_nodes USING gin (fact_ids)",
        (
            "CREATE INDEX ix_write_raw_sources_contribute_pending "
            "ON public.write_raw_sources (created_at) WHERE "
            "((contributed_to_public_at IS NULL) AND (canonical_url IS NOT NULL))"
        ),
        "CREATE INDEX ix_write_seed_facts_fact_id ON public.write_seed_facts (fact_id)",
        "CREATE INDEX ix_write_seeds_aliases ON public.write_seeds USING gin (aliases)",
        "CREATE INDEX ix_write_seeds_type_status ON public.write_seeds (node_type, status)",
    ):
        op.execute(idx_sql)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_write_seeds_updated_at', table_name='write_seeds')
    op.drop_index('ix_write_seeds_status', table_name='write_seeds')
    op.drop_index('ix_write_seeds_seed_uuid', table_name='write_seeds')
    op.drop_index('ix_write_seeds_phonetic_code', table_name='write_seeds')
    op.drop_table('write_seeds')
    op.drop_index('ix_wsr_parent_seed_key', table_name='write_seed_routes')
    op.drop_index('ix_wsr_child_seed_key', table_name='write_seed_routes')
    op.drop_table('write_seed_routes')
    op.drop_index('ix_write_seed_merges_updated_at', table_name='write_seed_merges')
    op.drop_table('write_seed_merges')
    op.drop_index('uq_wsf_seed_fact', table_name='write_seed_facts')
    op.drop_index('ix_write_seed_facts_updated_at', table_name='write_seed_facts')
    op.drop_index('ix_write_seed_facts_seed_key', table_name='write_seed_facts')
    op.drop_table('write_seed_facts')
    op.drop_index('ix_write_raw_sources_uri', table_name='write_raw_sources')
    op.drop_index('ix_write_raw_sources_updated_at', table_name='write_raw_sources')
    op.drop_index('ix_write_raw_sources_doi', table_name='write_raw_sources')
    op.drop_index('ix_write_raw_sources_content_hash', table_name='write_raw_sources')
    op.drop_index('ix_write_raw_sources_canonical_url', table_name='write_raw_sources')
    op.drop_table('write_raw_sources')
    op.drop_index('ix_write_prohibited_chunks_updated_at', table_name='write_prohibited_chunks')
    op.drop_index('ix_write_prohibited_chunks_content_hash', table_name='write_prohibited_chunks')
    op.drop_table('write_prohibited_chunks')
    op.drop_index('ix_write_page_fetch_log_url', table_name='write_page_fetch_log')
    op.drop_index('ix_write_page_fetch_log_updated_at', table_name='write_page_fetch_log')
    op.drop_table('write_page_fetch_log')
    op.drop_index('ix_write_nodes_updated_at', table_name='write_nodes')
    op.drop_index('ix_write_nodes_node_uuid', table_name='write_nodes')
    op.drop_index('ix_write_nodes_node_type', table_name='write_nodes')
    op.drop_table('write_nodes')
    op.drop_index('ix_write_node_versions_updated_at', table_name='write_node_versions')
    op.drop_index('ix_write_node_versions_node_key', table_name='write_node_versions')
    op.drop_table('write_node_versions')
    op.drop_index('uq_write_nfr_node_fact', table_name='write_node_fact_rejections')
    op.drop_index('ix_write_nfr_updated_at', table_name='write_node_fact_rejections')
    op.drop_index('ix_write_nfr_node_id', table_name='write_node_fact_rejections')
    op.drop_table('write_node_fact_rejections')
    op.drop_index('ix_write_node_counters_updated_at', table_name='write_node_counters')
    op.drop_table('write_node_counters')
    op.drop_index('ix_write_llm_usage_updated_at', table_name='write_llm_usage')
    op.drop_index('ix_write_llm_usage_task_type', table_name='write_llm_usage')
    op.drop_index('ix_write_llm_usage_message_id', table_name='write_llm_usage')
    op.drop_index('ix_write_llm_usage_conversation_id', table_name='write_llm_usage')
    op.drop_table('write_llm_usage')
    op.drop_index('ix_write_facts_updated_at', table_name='write_facts')
    op.drop_index('ix_write_facts_fact_type', table_name='write_facts')
    op.drop_index('ix_write_facts_dedup_pending', table_name='write_facts', postgresql_where=sa.text("dedup_status IN ('pending', 'in_progress')"))
    op.drop_table('write_facts')
    op.drop_index('ix_write_fact_sources_updated_at', table_name='write_fact_sources')
    op.drop_index('ix_write_fact_sources_fact_id', table_name='write_fact_sources')
    op.drop_table('write_fact_sources')
    op.drop_index('ix_write_edges_updated_at', table_name='write_edges')
    op.drop_index('ix_write_edges_target_key', table_name='write_edges')
    op.drop_index('ix_write_edges_source_key', table_name='write_edges')
    op.drop_table('write_edges')
    op.drop_index('ix_wec_seed_b_status', table_name='write_edge_candidates')
    op.drop_index('ix_wec_seed_a_status', table_name='write_edge_candidates')
    op.drop_table('write_edge_candidates')
    op.drop_index('ix_write_divergent_claims_updated_at', table_name='write_divergent_claims')
    op.drop_index('ix_write_divergent_claims_node_key', table_name='write_divergent_claims')
    op.drop_table('write_divergent_claims')
    op.drop_index('ix_write_dimensions_updated_at', table_name='write_dimensions')
    op.drop_index('ix_write_dimensions_node_key', table_name='write_dimensions')
    op.drop_table('write_dimensions')
    op.drop_index('ix_write_convergence_updated_at', table_name='write_convergence_reports')
    op.drop_table('write_convergence_reports')
    op.drop_table('sync_watermarks')
    op.drop_index('ix_sync_failures_status', table_name='sync_failures')
    op.drop_index('ix_sync_failures_next_retry_at', table_name='sync_failures')
    op.drop_table('sync_failures')
    # ### end Alembic commands ###
