"""Tool: read_node — Read a node's dimensions, edges, and structure.

Returns node overview (dimensions with suggested_concepts, connected edges,
stance summary for perspectives). Also enriches the node with any new facts
from the pool. Does NOT return fact content — use get_node_facts for that.

Costs 1 nav_budget if the node hasn't been visited; free if already in session.
"""

from __future__ import annotations

import logging
import uuid
from typing import Any

from kt_agents_core.state import AgentContext, PipelineState
from kt_worker_nodes.pipelines.enrichment import PoolEnricher

logger = logging.getLogger(__name__)

MAX_DIMENSION_CONTENT_LEN = 500
MAX_BATCH_SIZE = 10


async def read_node_impl(
    node_id: str,
    ctx: AgentContext,
    state: PipelineState,
) -> dict[str, Any]:
    """Read a node's dimensions, edges, and structural info.

    Also enriches the node with new facts from the pool (free, no budget cost).

    Args:
        node_id: UUID string of the node.
        ctx: Agent context with graph engine.
        state: Orchestrator state (mutated in-place for visited_nodes).

    Returns:
        Dict with node overview including dimensions and edges.
    """
    # Validate UUID
    try:
        nid = uuid.UUID(node_id)
    except (ValueError, AttributeError):
        return {"error": f"Invalid node_id: '{node_id}' is not a valid UUID."}

    # Fetch node
    node = await ctx.graph_engine.get_node(nid)
    if node is None:
        return {"error": f"Node not found: {node_id}"}

    # Budget check
    already_visited = node_id in state.visited_nodes
    nav_remaining = max(0, state.nav_budget - state.nav_used)

    if not already_visited:
        if nav_remaining <= 0:
            return {
                "error": "Nav budget exhausted — cannot read unvisited node.",
                "nav_remaining": 0,
            }
        # Charge 1 nav_budget
        state.visited_nodes.append(node_id)
        state.nav_used += 1
        state.exploration_path.append(node.concept)
        budget_cost = 1
    else:
        budget_cost = 0

    nav_remaining = max(0, state.nav_budget - state.nav_used)

    await ctx.graph_engine.increment_access_count(nid)

    await ctx.emit("activity_log", action=f"Reading node: '{node.concept}'", tool="read_node")
    await ctx.emit(
        "node_visited",
        data={
            "id": node_id,
            "concept": node.concept,
            "node_type": node.node_type,
        },
    )
    budget_data: dict[str, object] = {
        "nav_remaining": nav_remaining,
        "nav_total": state.nav_budget,
        "explore_remaining": state.explore_remaining,
        "explore_total": state.explore_budget,
    }
    scope = getattr(state, "scope", None)
    if scope is not None:
        budget_data["scope"] = scope
    await ctx.emit("budget_update", data=budget_data)

    # Enrich with new pool facts (free)
    enrich_result = await PoolEnricher(ctx).enrich(node)

    # Fetch dimensions (possibly regenerated by enrichment)
    dimensions = await ctx.graph_engine.get_dimensions(nid)

    # Fetch edges (both directions)
    edges = await ctx.graph_engine.get_edges(nid, direction="both")

    # Resolve edge targets to concept names and emit graph events
    edge_list: list[dict[str, Any]] = []
    for edge in edges:
        if edge.source_node_id == nid:
            target_id = edge.target_node_id
            direction = "outgoing"
        else:
            target_id = edge.source_node_id
            direction = "incoming"

        target_node = await ctx.graph_engine.get_node(target_id)
        target_concept = target_node.concept if target_node else "unknown"

        # Emit connected node so the frontend graph can render it
        if target_node is not None:
            await ctx.emit(
                "node_visited",
                data={
                    "id": str(target_id),
                    "concept": target_concept,
                    "node_type": getattr(target_node, "node_type", "concept"),
                },
            )

        # Emit existing edge so the frontend graph can draw the connection
        await ctx.emit(
            "edge_created",
            data={
                "id": str(edge.id),
                "source_node_id": str(edge.source_node_id),
                "target_node_id": str(edge.target_node_id),
                "relationship_type": edge.relationship_type,
                "weight": edge.weight,
                "justification": edge.justification,
            },
        )

        edge_list.append(
            {
                "target_node_id": str(target_id),
                "target_concept": target_concept,
                "relationship_type": edge.relationship_type,
                "weight": edge.weight,
                "direction": direction,
            }
        )

    # Get fact count (count only, no content)
    facts = await ctx.graph_engine.get_node_facts(nid)
    fact_count = len(facts)

    # Compute richness and staleness
    richness = ctx.graph_engine.compute_richness(node, fact_count, len(dimensions))
    is_stale = ctx.graph_engine.is_node_stale(node)

    # Build dimensions list (truncated content)
    dim_list: list[dict[str, Any]] = []
    for dim in dimensions:
        content = dim.content
        if len(content) > MAX_DIMENSION_CONTENT_LEN:
            content = content[:MAX_DIMENSION_CONTENT_LEN] + "..."
        dim_list.append(
            {
                "model_id": dim.model_id,
                "content": content,
                "confidence": dim.confidence,
                "suggested_concepts": dim.suggested_concepts or [],
                "batch_index": dim.batch_index,
                "fact_count": dim.fact_count,
                "is_definitive": dim.is_definitive,
            }
        )

    result: dict[str, Any] = {
        "node_id": node_id,
        "concept": node.concept,
        "node_type": node.node_type,
        "definition": node.definition,
        "fact_count": fact_count,
        "new_facts_linked": enrich_result.new_facts_linked,
        "dimensions_regenerated": enrich_result.dimensions_regenerated,
        "richness": richness,
        "is_stale": is_stale,
        "budget_cost": budget_cost,
        "nav_remaining": nav_remaining,
        "dimensions": dim_list,
        "edges": edge_list,
    }

    return result


async def read_nodes_impl(
    node_ids: list[str],
    ctx: AgentContext,
    state: PipelineState,
) -> dict[str, Any]:
    """Batch read multiple nodes.

    Reads are sequential (budget accounting requires it).

    Args:
        node_ids: List of UUID strings (capped at MAX_BATCH_SIZE).
        ctx: Agent context with graph engine.
        state: Orchestrator state (mutated in-place).

    Returns:
        Dict with results list and summary.
    """
    capped = node_ids[:MAX_BATCH_SIZE]
    results: list[dict[str, Any]] = []

    for nid in capped:
        result = await read_node_impl(nid, ctx, state)
        results.append(result)

    total_cost = sum(r.get("budget_cost", 0) for r in results)
    errors = [r for r in results if "error" in r]

    return {
        "results": results,
        "count": len(results),
        "total_budget_cost": total_cost,
        "errors": len(errors),
        "capped": len(node_ids) > MAX_BATCH_SIZE,
    }
